---
title: "Analysis of ActPass paradigm session"
format:
  html:
    code-fold: true
    page-layout: full
jupyter: python3
---


```{python}
import os 
import glob
import json

RootAnalysisFolder = os.path.split(os.path.split(os.getcwd())[0])[0]
from termcolor import colored
import mne
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(15,8)
plt.rcParams["figure.dpi"] = 300.
import sys
sys.path.append(RootAnalysisFolder)

from AddPyABA_Path import PyABA_path
sys.path.append(PyABA_path)
import gaze_tools,py_tools

from ActPass_fun import ActPass
```


*fif file name definition

```{python}

RootFolder =  os.path.split(RootAnalysisFolder)[0]

RootDirectory_RAW = RootFolder + '/_data/FIF/'
RootDirectory_Results = RootFolder + '/_results/'
FifFileName = RootDirectory_RAW + "***SUJ***\***SUJ***_ActPass.raw.fif"

SUBJECT_NAME = os.path.split(os.path.split(FifFileName)[0])[1]

```


Read Raw File

```{python}

# Read fif filename 
raw_ActPass = ActPass(FifFileName)

```


## Plot the STD ERP in DIVerted Attention Condition and detect the significant components

```{python}
fig_StdDiv_EmergCompo = raw_ActPass.SignificativeComponante('STD/DIV',-0.2, 1.5, (-0.2,0),'g',0.75)
```


## Plot the STD ERP in FOCused Attention Condition and detect the significant components

```{python}
fig_StdFoc_EmergCompo = raw_ActPass.SignificativeComponante('STD/FOC',-0.2, 1.5, (-0.2,0),'r',0.75)
```



## Plot the DEV ERP in DIVerted Attention Condition and detect the significant components

```{python}
fig_DevDiv_EmergCompo = raw_ActPass.SignificativeComponante('DEV/DIV',-0.2, 1.5, (-0.2,0),'g',2)
```


## Plot the DEV ERP in FOCused Attention Condition and detect the significant components

```{python}
fig_DevFoc_EmergCompo = raw_ActPass.SignificativeComponante('DEV/FOC',-0.2, 1.5, (-0.2,0),'r',2)
```


## Compare STD ERPs in FOCused Attention and in DIVerted Attention Conditions
```{python}
fig_STD_FocVsDiv = raw_ActPass.StimComp2Cond(['STD/FOC','STD/DIV']   ,-0.2, 1.5, (-0.2,0),['r','g'],[0.75,0.75])
```	

## Compare DEV ERPs in FOCused Attention and in DIVerted Attention Conditions
```{python}
fig_DEV_FocVsDiv = raw_ActPass.StimComp2Cond(['DEV/FOC','DEV/DIV']   ,-0.2, 1.5, (-0.2,0),['r','g'],[2.0,2.0])
```	
		
## Compare STD and DEV ERPs in DIVerted Attention Condition
```{python}
fig_StdDev_DIV = raw_ActPass.CompareSTD_DEV(['STD/DIV','DEV/DIV'],-0.2, 1.5, (-0.2,0),['g','g'],[0.75,2])
```			
		
## Compare STD and DEV ERPs in FOCused Attention Condition
```{python}
fig_StdDev_FOC = raw_ActPass.CompareSTD_DEV(['STD/FOC','DEV/FOC'],-0.2, 1.5, (-0.2,0),['r','r'],[0.75,2])
```				
		

## Compute MMN responses in FOCused Attention and in DIVerted Attention Conditions 
```{python}
fig_mmn = raw_ActPass.Analysis_MMN([['STD/FOC','DEV/FOC'],['STD/DIV','DEV/DIV']],-0.2, 1.5, (-0.2,0),['r','g'],[3,3])
```		

## Compute the COUNT Effect : compare STD and DEV ERPs computed within the Region of Interest (ROI) consisting of Fz, Cz, and Pz electrodes under the FOCused Attention Condition
```{python}
fig_CountEffect,CountEffect_OK =  raw_ActPass.Compare_STDvsDEV_FocCondition(['STD/FOC','DEV/FOC'], -0.2, 1.5, (-0.2,0),['r','r'],[0.75,2],[0.25,0.8],['Fz','Cz','Pz'],0.05)
if CountEffect_OK:
	print(colored("COUNT EFFECT", 'green'))
else:
	print(colored("NO COUNT EFFECT", 'red'))
```	


## Compute the FOC vs DIV Effect : compare DEV ERPs computed within the Region of Interest (ROI) consisting of Fz, Cz, and Pz electrodes under the DIVerted Attention and the FOCused Attention Conditions
```{python}
fig_DEV_FocVsDiv,FocDivEffect_OK =  raw_ActPass.Compare_DEV_2Cond(['DEV/FOC','DEV/DIV'], -0.2, 1.5, (-0.2,0),['r','g'],[2.0,2.0],[0.25,0.8],['Fz','Cz','Pz'],0.05)
if FocDivEffect_OK:
	print(colored(" FOC vs DIV EFFECT ", 'green'))
else:
	print(colored("NO FOC vs DIV EFFECT ", 'red'))

```	
	
	
## Compare Heart Rate under the DIVerted Attention and the FOCused Attention Conditions
```{python}
fig_HR = raw_ActPass.HeartRate_analysis([['STD/FOC','DEV/FOC'],['STD/DIV','DEV/DIV']])
```


## Compare Pupil Diameter under the DIVerted Attention and the FOCused Attention Conditions
```{python}
fig_Pupill = raw_ActPass.PupilDiam_analysis([['STD/FOC','DEV/FOC'],['STD/DIV','DEV/DIV']])
```



## Respiration analysis in DIV condition
```{python}
RSP_RATE_Mean_Div,RSP_RATE_Std_Div, RSP_Amplitude_Mean_Div, RSP_Amplitude_Std_Div = raw_ActPass.RespirationSynchrony(raw_ActPass.mne_raw,['STD/DIV','DEV/DIV']) # DIV condition
```

## Respiration analysis in FOC condition
```{python}
RSP_RATE_Mean_Foc,RSP_RATE_Std_Foc, RSP_Amplitude_Mean_Foc, RSP_Amplitude_Std_Foc = raw_ActPass.RespirationSynchrony(raw_ActPass.mne_raw,['STD/FOC','DEV/FOC']) # FOC condition
```


# Save results computed from gaze data in a *json file
```{python}
if not(os.path.exists(RootDirectory_Results + SUBJECT_NAME)):
	os.mkdir(RootDirectory_Results + SUBJECT_NAME)
SaveDataFilename = RootDirectory_Results + SUBJECT_NAME + "/" + SUBJECT_NAME + "_ActPass.json"
Results = {"CountEffect" :CountEffect_OK, "FocDivEffect" : FocDivEffect_OK}

with open(SaveDataFilename, "w") as outfile: 
	   json.dump(Results, outfile)
	   

py_tools.append_to_json_file(SaveDataFilename, {'Resp_Rate_MEAN_Div':RSP_RATE_Mean_Div,'Resp_Rate_STD_Div':RSP_RATE_Std_Div,'Resp_Amp_MEAN_Div':RSP_Amplitude_Mean_Div,'Resp_Amp_STD_Div':RSP_Amplitude_Std_Div})	 
py_tools.append_to_json_file(SaveDataFilename, {'Resp_Rate_MEAN_Foc':RSP_RATE_Mean_Foc,'Resp_Rate_STD_Foc':RSP_RATE_Std_Foc,'Resp_Amp_MEAN_Foc':RSP_Amplitude_Mean_Foc,'Resp_Amp_STD_Foc':RSP_Amplitude_Std_Foc})	 
   
	   
```